# Generated by Django 3.1 on 2020-09-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='point',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.IntegerField(),
        ),
    ]
